// <auto-generated />
namespace Tastebook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test231 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test231));
        
        string IMigrationMetadata.Id
        {
            get { return "201705261416288_test231"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
